### ISSUE TITLE
Is there a link to inthe Lipp Lab

### ISSUE THREAD

**Issue by ygechn** [epid8060fall2019/meganlott-introduction#1]
Hi, I really like your introduction website. It is detail and some fun pictures, however, I am not familiar with your lab: inthe Lipp Lab. Is there any link or resource I can look to see what a major picture of your lab is?

Thank you, 

Yang

**Comment by meganejlott** [comment]
Hi Yang! Thanks so much for your feedback and your interest in the Lipp Lab. I've added a link to the lab into the introduction. The lab's site might provide more insight into our research on environmental and marine microbiology. Please let me know if you have any more questions or comments! 

Thank you!
Megan
